#cloud-config
write_files:
  - content: |
      [Unit]
      Description=TFE agent
      
      [Service]
      Type=simple
      Environment="TFC_ADDRESS=https://${dns_hostname}.${dns_zonename}"
      Environment="TFC_AGENT_TOKEN=AGENT_TOKEN_WILL_BE_PLACED_HERE"
      Environment="TFC_AGENT_NAME=INSTANCE_ID_WILL_BE_PLACED_HERE"
      User=root
      WorkingDirectory=/opt/tfe-agent
      ExecStart=/opt/tfe-agent/tfc-agent
      Restart=always
      RestartSec=30
      TimeoutStartSec=30
      TimeoutStopSec=30
      
      [Install]
      WantedBy=multi-user.target
    permissions: '0750'
    path: /etc/systemd/system/tfe-agent.service
  - content: |
      #!/usr/bin/env bash
      until ping -c1 archive.ubuntu.com &>/dev/null; do
        echo "waiting for networking to initialise"
        sleep 3 
      done
      apt-get update
      apt-get install -y jq awscli unzip 
      let i=0
      while true; do
          set -o pipefail
          AGENT_TOKEN_SECRET=`aws secretsmanager get-secret-value --secret-id ${agent_token_secret} --region ${region} | jq --raw-output '.SecretString | select(. != null)'`
          if [ $? -ne 0 ]
          then
              # lets wait 10 mins, max
              if [ $i -gt 10 ] ; then
                  echo "err: timeout waiting for AGENT_TOKEN_SECRET"
                  exit 1
              fi
              echo "No agent token known"
              echo "Will continue in 1 minute and check again"
              sleep 60
              let i++
          else
              export AGENT_TOKEN_SECRET
              echo "AGENT_TOKEN_SECRET has a known value"
              break
          fi
      done  
      mkdir -p /opt/tfe-agent    
      curl https://releases.hashicorp.com/tfc-agent/1.4.0/tfc-agent_1.4.0_linux_amd64.zip --output /tmp/tfc-agent_1.4.0_linux_amd64.zip   
      unzip /tmp/tfc-agent_1.4.0_linux_amd64.zip  -d /opt/tfe-agent
      sed -i "s/AGENT_TOKEN_WILL_BE_PLACED_HERE/$AGENT_TOKEN_SECRET/g" /etc/systemd/system/tfe-agent.service 
      export INSTANCE_ID=`curl http://169.254.169.254/latest/meta-data/instance-id`
      sed -i "s/INSTANCE_ID_WILL_BE_PLACED_HERE/$INSTANCE_ID/g" /etc/systemd/system/tfe-agent.service
      systemctl daemon-reload
      systemctl start tfe-agent
      systemctl enable tfe-agent.service
    permissions: '0750'
    path: /var/tmp/get_token.sh        
runcmd:
  - bash /var/tmp/get_token.sh
  - curl -sL https://raw.githubusercontent.com/kikitux/curl-bash/master/provision/add_github_user_public_keys.sh | GITHUB_USER=kikitux bash
  - curl -sL https://raw.githubusercontent.com/kikitux/curl-bash/master/provision/add_github_user_public_keys.sh | GITHUB_USER=munnep bash

